import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

const root = fileURLToPath(new URL('.', import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    root,
    environment: 'node',
    include: ['tests/**/*.test.{ts,tsx}'],
    exclude: ['tests/integration/**'],
    setupFiles: ['./tests/setup.ts'],
    clearMocks: true,
    mockReset: true,
    restoreMocks: true,
    unstubEnvs: true,
    unstubGlobals: true,
    passWithNoTests: false,
    testTimeout: 10_000,
    hookTimeout: 10_000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'src/components/DocumentLocale.tsx',
        'src/components/FilterDrawer.tsx',
        'src/components/PortalRefreshRedirect.tsx',
        'src/components/ThemeToggle.tsx',
        'src/components/guest/guestValidation.ts',
        'src/components/maps/leafletPopup.ts',
        'src/components/navigation/menuLinks.ts',
        'src/lib/auth/admin.ts',
        'src/lib/apiErrorHandler.ts',
        'src/lib/collections.ts',
        'src/lib/contactLinks.ts',
        'src/lib/crypto.ts',
        'src/lib/csv.ts',
        'src/lib/data.ts',
        'src/lib/dateUtils.ts',
        'src/lib/guestSession.ts',
        'src/lib/internalFetch.ts',
        'src/lib/jsonLd.ts',
        'src/lib/mapUtils.ts',
        'src/lib/net/getClientIp.ts',
        'src/lib/observability-contracts.ts',
        'src/lib/phone.ts',
        'src/lib/portalBookingEligibility.ts',
        'src/lib/portalRefreshClient.ts',
        'src/lib/propertyTime.ts',
        'src/lib/prismaPgConfig.ts',
        'src/lib/redaction.ts',
        'src/lib/runtime-env-schema.js',
        'src/lib/security-config.ts',
        'src/lib/sensitiveRateLimit.ts',
        'src/lib/safeLocalPath.ts',
        'src/lib/site.ts',
        'src/lib/stayRequestPhone.ts',
        'src/lib/travelFormat.ts',
        'src/lib/userFacingErrors.ts',
      ],
      exclude: ['src/generated/**', '**/*.d.ts'],
      thresholds: {
        lines: 89,
        functions: 91,
        branches: 82,
        statements: 88,
      },
    },
  },
});
