import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitest/config';

const root = fileURLToPath(new URL('.', import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    root,
    environment: 'node',
    include: ['tests/**/*.test.{ts,tsx}'],
    exclude: ['tests/integration/**'],
    setupFiles: ['./tests/setup.ts'],
    clearMocks: true,
    mockReset: true,
    restoreMocks: true,
    unstubEnvs: true,
    unstubGlobals: true,
    passWithNoTests: false,
    testTimeout: 10_000,
    hookTimeout: 10_000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'src/components/DocumentLocale.tsx',
        'src/components/PortalRefreshRedirect.tsx',
        'src/components/availability/format.ts',
        'src/components/availability/plannerState.ts',
        'src/components/guest/guestValidation.ts',
        'src/components/guide/guideEntries.ts',
        'src/components/guide/guideFilters.ts',
        'src/components/maps/leafletPopup.ts',
        'src/components/maps/tileSource.ts',
        'src/components/shell/LanguageSwitch.tsx',
        'src/components/shell/MotionSwitch.tsx',
        'src/components/shell/ThemeSwitch.tsx',
        'src/components/shell/shellLinks.ts',
        'src/lib/auth/admin.ts',
        'src/lib/apiErrorHandler.ts',
        'src/lib/availability/calendarDate.ts',
        'src/lib/availability/calendarSync.ts',
        'src/lib/availability/icalFetch.ts',
        'src/lib/availability/icalParser.ts',
        'src/lib/availability/money.ts',
        'src/lib/availability/stayQuote.ts',
        'src/lib/bookingOutbox.ts',
        'src/lib/collections.ts',
        'src/lib/contactLinks.ts',
        'src/lib/whatsapp.ts',
        'src/lib/crypto.ts',
        'src/lib/data.ts',
        'src/lib/featureFlags.ts',
        'src/lib/guestSession.ts',
        'src/lib/jsonLd.ts',
        'src/lib/net/clientIdentity.ts',
        'src/lib/net/getClientIp.ts',
        'src/lib/net/sameOrigin.ts',
        'src/lib/operationalMonitor.ts',
        'src/lib/phone.ts',
        'src/lib/portalAuthService.ts',
        'src/lib/portalBookingEligibility.ts',
        'src/lib/portalClaimExchange.ts',
        'src/lib/portalRefreshClient.ts',
        'src/lib/propertyTime.ts',
        'src/lib/prismaPgConfig.ts',
        'src/lib/prisma-repositories/availabilityRepository.ts',
        'src/lib/prisma-repositories/checkInRequestRepository.ts',
        'src/lib/prisma-repositories/ratePeriodRepository.ts',
        'src/lib/privacyService.ts',
        'src/lib/redaction.ts',
        'src/lib/runtime-env-schema.js',
        'src/lib/security-config.ts',
        'src/lib/sensitiveRateLimit.ts',
        'src/lib/safeLocalPath.ts',
        'src/lib/site.ts',
        'src/lib/userFacingErrors.ts',
      ],
      exclude: ['src/generated/**', '**/*.d.ts'],
      thresholds: {
        lines: 89,
        functions: 91,
        branches: 82,
        statements: 88,
      },
    },
  },
});
