#!/usr/bin/env node
/*
 * Ensure a SECURITY_PEPPER exists in .env.local for local development.
 * - Idempotent: does nothing if SECURITY_PEPPER already present.
 * - Safe: writes only to .env.local which is ignored by git in this repo.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const envPath = path.resolve(process.cwd(), '.env.local');

function readEnv(p) {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch {
    return '';
  }
}

const existing = readEnv(envPath);

// Prepare lines to append for any missing secrets
const toAppend = [];
const header = '\n# Generated by scripts/ensure-pepper.js — keep this file private and do not commit\n';

// SECURITY_PEPPER
if (!/^\s*SECURITY_PEPPER\s*=\s*/m.test(existing)) {
  const pepper = crypto.randomBytes(32).toString('hex');
  toAppend.push(`SECURITY_PEPPER=${pepper}`);
}

// SECURITY_ENC_KEY_HEX (encryption key in hex)
if (!/^\s*SECURITY_ENC_KEY_HEX\s*=\s*/m.test(existing)) {
  // 32 bytes (256 bits) recommended for symmetric keys
  const encKey = crypto.randomBytes(32).toString('hex');
  toAppend.push(`SECURITY_ENC_KEY_HEX=${encKey}`);
}

if (toAppend.length === 0) {
  console.log('All expected secrets present in .env.local — no action taken.');
  process.exit(0);
}

const content = header + toAppend.map((s) => s + '\n').join('');
try {
  fs.appendFileSync(envPath, content, { encoding: 'utf8', mode: 0o600 });
  try {
    // set restrictive permissions where supported
    fs.chmodSync(envPath, 0o600);
  } catch {
    // ignore chmod failures on platforms that don't support it
  }
  toAppend.forEach((line) => console.log(`Generated ${line.split('=')[0]} and appended to .env.local (local only).`));
  console.log('Do NOT commit .env.local. Use your platform secret store for CI/production.');
} catch (err) {
  console.error('Failed to write .env.local:', err.message || err);
  process.exit(2);
}
