#!/usr/bin/env node
/*
 * Ensure local-only secrets exist in .env.local for development.
 * - Idempotent: appends only missing values.
 * - Safe: writes only to .env.local which is ignored by git in this repo.
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const envPath = path.resolve(process.cwd(), '.env.local');

function readEnv(p) {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch {
    return '';
  }
}

const existing = readEnv(envPath);

// Prepare lines to append for any missing local development values.
const toAppend = [];
const header = '\n# Generated by scripts/ensure-pepper.js — keep this file private and do not commit\n';

if (!/^[^\S\n]*DATABASE_URL[^\S\n]*=[^\S\n]*\S/m.test(existing)) {
  // The docker-compose dev database; mirrors fallback_database_url in scripts/system-orchestrator.sh.
  const url = new URL('postgresql://localhost');
  url.username = process.env.POSTGRES_USER || 'devuser';
  url.password = process.env.POSTGRES_PASSWORD || 'devpass';
  url.port = process.env.POSTGRES_PORT || '5433';
  url.pathname = `/${encodeURIComponent(process.env.POSTGRES_DB || 'site_dev')}`;
  toAppend.push(`DATABASE_URL=${url.href}`);
}

if (!/^[^\S\n]*SECURITY_PEPPER[^\S\n]*=[^\S\n]*\S/m.test(existing)) {
  const pepper = crypto.randomBytes(32).toString('hex');
  toAppend.push(`SECURITY_PEPPER=${pepper}`);
}

if (!/^[^\S\n]*CLAIM_TOKEN_PEPPER[^\S\n]*=[^\S\n]*\S/m.test(existing)) {
  toAppend.push(`CLAIM_TOKEN_PEPPER=${crypto.randomBytes(32).toString('hex')}`);
}

if (!/^\s*GUEST_JWT_SECRET\s*=\s*/m.test(existing)) {
  const guestJwtSecret = crypto.randomBytes(32).toString('hex');
  toAppend.push(`GUEST_JWT_SECRET=${guestJwtSecret}`);
}

if (!/^[^\S\n]*ORIGIN_PROXY_SHARED_SECRET[^\S\n]*=[^\S\n]*\S/m.test(existing)) {
  // Local stand-in for the Nginx attestation; `npm run dev:proxy` sends it (scripts/dev-proxy.mjs).
  toAppend.push(`ORIGIN_PROXY_SHARED_SECRET=${crypto.randomBytes(32).toString('hex')}`);
}

if (!/^\s*GUEST_WIFI_NETWORK\s*=\s*/m.test(existing)) {
  toAppend.push('GUEST_WIFI_NETWORK=local-guest-network');
}

if (!/^\s*GUEST_WIFI_PASSWORD\s*=\s*/m.test(existing)) {
  const guestWifiPassword = crypto.randomBytes(16).toString('base64url');
  toAppend.push(`GUEST_WIFI_PASSWORD=${guestWifiPassword}`);
}

if (toAppend.length === 0) {
  console.log('All expected secrets present in .env.local — no action taken.');
  process.exit(0);
}

const content = header + toAppend.map((s) => s + '\n').join('');
try {
  fs.appendFileSync(envPath, content, { encoding: 'utf8', mode: 0o600 });
  try {
    // set restrictive permissions where supported
    fs.chmodSync(envPath, 0o600);
  } catch {
    // ignore chmod failures on platforms that don't support it
  }
  toAppend.forEach((line) => console.log(`Generated ${line.split('=')[0]} and appended to .env.local (local only).`));
  console.log('Do NOT commit .env.local. Use your deployment platform secret store in production.');
} catch (err) {
  console.error('Failed to write .env.local:', err.message || err);
  process.exit(2);
}
