#!/usr/bin/env tsx
/**
 * generate-house-photos.ts
 * - Ensures public/house images have pre-generated low quality blur placeholders (LQIP)
 * - Outputs a JSON module (src/data/housePhotos.ts) consumed by the house page.
 * - Falls back gracefully if sharp is not installed.
 */
import fs from 'node:fs';
import path from 'node:path';

const HOUSE_DIR = path.join(process.cwd(), 'public', 'house');
const OUT_FILE = path.join(process.cwd(), 'src', 'data', 'housePhotos.ts');

interface PhotoMeta { src: string; width: number; height: number; blurDataURL: string; }

async function main() {
  if (!fs.existsSync(HOUSE_DIR)) {
    console.warn('[house-photos] no public/house directory, skipping');
    return;
  }
  const files = fs.readdirSync(HOUSE_DIR).filter(f => /(jpe?g|png)$/i.test(f));
  if (!files.length) {
    console.warn('[house-photos] no image files found, skipping');
    return;
  }
  let size: any = null;
  try { size = (await import('image-size')).default || (await import('image-size')); } catch {}
  let sharp: any = null;
  try { sharp = (await import('sharp')).default || (await import('sharp')); } catch {
    console.warn('[house-photos] sharp not installed, using naive blur extraction (first bytes)');
  }
  const metas: PhotoMeta[] = [];
  for (const f of files.slice(0, 12)) { // safety cap
    const abs = path.join(HOUSE_DIR, f);
    const buf = fs.readFileSync(abs);
    let width = 0; let height = 0;
    try { const dim = size?.imageSize ? size.imageSize(abs) : (size?.default ? size.default(abs) : size(abs)); width = dim.width; height = dim.height; } catch {}
    let blur = '';
    if (sharp) {
      try {
        const mini = await sharp(buf).resize(24).jpeg({ quality: 40 }).toBuffer();
        blur = `data:image/jpeg;base64,${mini.toString('base64')}`;
      } catch (e) {
        blur = `data:image/jpeg;base64,${buf.slice(0,1200).toString('base64')}`;
      }
    } else {
      blur = `data:image/jpeg;base64,${buf.slice(0,1200).toString('base64')}`;
    }
    metas.push({ src: `/house/${f}`, width, height, blurDataURL: blur });
  }
  const file = `// Auto-generated by scripts/generate-house-photos.ts
export interface HousePhoto { src: string; width: number; height: number; blurDataURL: string; }
export const housePhotos: HousePhoto[] = ${JSON.stringify(metas, null, 2)};
`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, file, 'utf8');
  console.log(`[house-photos] wrote ${metas.length} entries to ${path.relative(process.cwd(), OUT_FILE)}`);
}

main().catch(err => { console.error('[house-photos] failed', err); process.exitCode = 1; });
